name: model
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.6.2
  build_runner: ^2.4.1
  freezed: ^2.3.3